### ISSUE TITLE
Standard naming convention?

### ISSUE THREAD

**Issue by DaveC426913** [jdpedrie/angularjs-camelCase-to-human-filter#6]
It must be me but I cannot figure out how to implement this. I get a Unknown provider: camelCaseToHumanProvider error.

I think my problem is that this doesn't seem to be a familiar framework for fllters. I don't know what camelcase-browser is supposed to be (I assume that's the filter itself) or what index.js is.

It's a shame. It's exactly what I need but I'll have to keep looking.

**Comment by jdpedrie** [comment]
Hello!

You need to include `camelcase-browser.js`. This gives you everything needed to use the filter. `index.js` is not compiled with its dependencies, so it's useful for some cases where you already have a build pipeline using browserify or something.

What version of Angular are you using? And you've added `camelcaseToHuman` to your module dependencies?

**Comment by jdpedrie** [comment]
I looked at the readme, and while I mentioned the part about adding the filter to your module, I left it out of the full usage example (since updated).

You should have something like this:

````js
module('MyApp', ['camelCaseToHuman'])
````

**Comment by DaveC426913** [comment]
Here is what I have done:
- contents of camelcase-browser.js placed in <app_path>/filters/camelCaseToHuman.js
- added  `<script src="<app_path>/filters/camelCaseToHuman.js"></script>` to index.html
- ordersController.$inject = ['camelCaseToHuman']; function ordersController(camelCaseToHuman) {...}
- view: {{myValue | camelCaseToHuman}}

This is the error I get:
Error: $injector: Unknown provider: camelCaseToHumanProvider

Sorry, I can't parse the contents of camelcase-browser.js, so I can't debug it.
